joint_planner:
  ros__parameters:
    model:
      action_dim: 10
      observation_dim: 450 # 45 * 10
      observation_history_length: 10
      action_scale:
        - 0.25
        - 0.25
        - 0.25
        - 0.25
        - 0.25
        - 0.25
        - 0.25
        - 0.25
        - 0.25
        - 0.25
      default_joint_positions:
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0

      joint_names:
        - "L_hip_joint"
        - "L_hip2_joint"
        - "L_thigh_joint"
        - "L_calf_joint"
        - "L_toe_joint"
        - "R_hip_joint"
        - "R_hip2_joint"
        - "R_thigh_joint"
        - "R_calf_joint"
        - "R_toe_joint"

      gains:
        kps: [405.001190519582, 592.1762640653615, 631.6546816697189, 303.1824036761838, 405.001190519582, 592.1762640653615, 631.6546816697189, 303.1824036761838, 161.4548844765406, 161.4548844765406]
        kds: [25.783176571717576,   37.69911184307752,   40.21238596594935,   19.301191281418827,   25.783176571717576,   37.69911184307752,   40.21238596594935,   19.301191281418827,  10.278537180308943,  10.278537180308943]

      cmd_limits:
        max_linear_velocity_x: 0.35   # m/s
        max_linear_velocity_y: 0.0   # m/s
        max_angular_velocity:  1.0   # rad/s
      
      policy_file_path: "/home/gene/DanielWorkspace/ros2_ws/src/joint_planner/src/RLPolicy/exported_policy/policy_81cm_10obs_eta2.onnx"
      device: "cpu"
      control_rate_hz: 50.0         # Hz
  
    hw:
      joint_names:
        - "R_hip_joint"
        - "R_hip2_joint"
        - "R_thigh_joint"
        - "R_calf_joint"
        - "L_hip_joint"
        - "L_hip2_joint"
        - "L_thigh_joint"
        - "L_calf_joint"
        - "L_toe_joint"
        - "R_toe_joint" 
 

    default_gains:
      kps: [405.001190519582, 592.1762640653615, 631.6546816697189, 303.1824036761838, 405.001190519582, 592.1762640653615, 631.6546816697189, 303.1824036761838, 161.4548844765406, 161.4548844765406]
      kds: [25.783176571717576,   37.69911184307752,   40.21238596594935,   19.301191281418827,   25.783176571717576,   37.69911184307752,   40.21238596594935,   19.301191281418827,  10.278537180308943,  10.278537180308943]

      
    positions:
      standing: [0.0, 0.0, 0.2, -0.34, 0.0, 0.0, 0.2, -0.34, 0.2, 0.2]
      default: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      kneeling: [0.0, 0.0, 0.0, 0.0, -0.5735, -0.5735, 1.147, 1.147, -0.5735, -0.5735]

    
